export enum UserStatus {
  NEW = 'NEW',
  GET_STARTED = 'GET_STARTED',
  CHOOSE_PROFESSION = 'CHOOSE_PROFESSION',
  CONNECT_SOCIAL = 'CONNECT_SOCIAL',
  CONFIGURE_WEBSITE = 'CONFIGURE_WEBSITE',
  PARSING = 'PARSING',
  PARSING_DONE = 'PARSING_DONE',
  CHOOSE_DESIGN = 'CHOOSE_DESIGN',
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}
